[package]
authors = ["Gaute Hope <eg@gaute.vetsj.com>"]
edition = "2018"
keywords = ["hdf"]
license = "LGPL"
name = "hidefix"
repository = "https://github.com/gauteh/hidefix"
version = "0.0.0"

[dependencies]
anyhow = "*"
async-stream = "*"
byte-slice-cast = "*"
futures = "*"
futures-core = "*"
futures-util = "*"
itertools = "*"
lru = "*"
strength_reduce = "*"

[dependencies.flate2]
features = ["zlib"]
version = "*"

[dependencies.hdf5]
branch = "hidefix"
git = "https://github.com/gauteh/hdf5-rust"

[dependencies.hdf5-sys]
branch = "hidefix"
features = ["static", "zlib"]
git = "https://github.com/gauteh/hdf5-rust"

[dependencies.rio]
optional = true
version = "*"

[dependencies.serde]
features = ["derive"]
version = "*"

[dependencies.tokio]
features = ["sync"]
version = "*"

[dev-dependencies]
byteorder = "*"
rand = "*"
ndarray = "*"
serde_json = "*"
rayon = "*"
bincode = "*"

[features]
io_uring = ["rio"]
