[package]
authors = ["Gaute Hope <eg@gaute.vetsj.com>"]
edition = "2018"
keywords = ["hdf", "async", "concurrency"]
license = "LGPL-3.0-or-later"
name = "hidefix"
repository = "https://github.com/gauteh/hidefix"
description = "Concurrent HDF5 and NetCDF4 reader (experimental)"
version = "0.1.0"

[dependencies]
anyhow = "*"
async-stream = "*"
bincode = "*"
byte-slice-cast = "*"
byteorder = "*"
bytes = "*"
flexbuffers = "*"
futures = "*"
futures-core = "*"
futures-util = "*"
itertools = "*"
libdeflater = "*"
lru = "*"
serde_bytes = "*"
strength_reduce = "*"
zerocopy = "*"

[dependencies.serde]
features = ["derive"]
version = "*"

[dependencies.tokio]
features = ["sync"]
version = "*"

[dependencies.hdf5]
version = "0.7.0"

[dependencies.hdf5-sys]
version = "0.7.0"

[dev-dependencies]
async-std = "*"
byteorder = "*"
ndarray = "*"
rand = "*"
rayon = "*"

[features]
default = ["static"]
static = ["hdf5-sys/static", "hdf5-sys/zlib"]
