[package]
authors = ["Gaute Hope <eg@gaute.vetsj.com>"]
edition = "2018"
keywords = ["hdf", "async", "concurrency"]
license = "LGPL-3.0-or-later"
name = "hidefix"
repository = "https://github.com/gauteh/hidefix"
description = "Concurrent HDF5 and NetCDF4 reader (experimental)"
version = "0.2.0"

[dependencies]
anyhow = "1.0.33"
async-stream = "0.3.0"
bincode = "1.3.1"
byte-slice-cast = "1.0.0"
byteorder = "1.3.4"
bytes = "0.5.0"
flexbuffers = "0.1.1"
futures = "0.3.7"
futures-core = "0.3.7"
futures-util = "0.3.7"
itertools = "0.9.0"
libdeflater = "0.5.0"
lru = "0.6.0"
serde_bytes = "0.11.5"
strength_reduce = "0.2.3"
zerocopy = "0.3.0"
libc = "0.2.80"
hdf5 = "0.7.0"
hdf5-sys = "0.7.0"
log = "0.4.11"

[dependencies.serde]
features = ["derive"]
version = "1.0.117"

[dependencies.tokio]
features = ["sync"]
version = "0.3.2"

[dev-dependencies]
ndarray = "0.13.1"
rand = "0.7.3"
rayon = "1.5.0"
sled = "0.34.4"

[patch.crates-io]
hdf5 = { git = "https://github.com/gauteh/hdf5-rust", branch = "hidefix" }
hdf5-sys = { git = "https://github.com/gauteh/hdf5-rust", branch = "hidefix" }

[features]
default = ["static"]
static = ["hdf5-sys/static", "hdf5-sys/zlib"]
fast-index = ["static"]

